repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
  # Avoid potential problems with py.test if __init__.py files are missing
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args: ["--create", "--python-folders", "htc,htc_projects,paper"]
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: "44e8fc9"
    hooks:
      - id: validate-cff
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        # mkdocs uses custom tags
        args: [--unsafe]
      - id: check-toml
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: mixed-line-ending
      - id: end-of-file-fixer
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: check-notebooks
        name: Check notebooks for common errors
        entry: python hooks/check_notebooks.py
        language: system
        types: [jupyter]
      - id: check-public-readme
        name: Check for common mistakes in the public README
        entry: python hooks/check_public_readme.py
        language: system
        types: [file]
        files: ^README_public.md$
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
