services:
  imsy-htc-base:
    build:
      context: ..
      dockerfile: dependencies/base.Dockerfile
    image: imsy-htc-base
  imsy-htc:
    build:
      context: ..
      dockerfile: dependencies/Dockerfile
      additional_contexts:
        imsy-htc-base: "service:imsy-htc-base"
    image: imsy-htc
    container_name: imsy-htc
    network_mode: host # e.g. for Jupyter Lab
    shm_size: 10gb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # This allows Docker containers to be start from inside the container, but as siblings and not nested (https://stackoverflow.com/a/33003273/2762258)
    # Required to get copy-on-write to work: https://github.com/moby/moby/issues/18191#issuecomment-159280820
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
