name: Docker Images

on: [push, pull_request]

jobs:
  docker-image:
    name: Create Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get version number
        run: |
          PACKAGE_VERSION=${GITHUB_REF_NAME#v}
          echo "Package version: $PACKAGE_VERSION"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
    
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dependencies/base.Dockerfile
          tags: |
            ghcr.io/imsy-dkfz/imsy-htc-base:${{ env.PACKAGE_VERSION }}
            ghcr.io/imsy-dkfz/imsy-htc-base:latest
            imsy-htc-base:latest
          cache-from: type=registry,ref=ghcr.io/imsy-dkfz/imsy-htc-base:buildcache

      - name: Build main image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dependencies/Dockerfile
          tags: |
            ghcr.io/imsy-dkfz/imsy-htc:${{ env.PACKAGE_VERSION }}
            ghcr.io/imsy-dkfz/imsy-htc:latest
          push: true
          cache-from: type=registry,ref=ghcr.io/imsy-dkfz/imsy-htc:buildcache
          cache-to: type=registry,ref=ghcr.io/imsy-dkfz/imsy-htc:buildcache,mode=max
