name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt --use-pep517
        pip install pytest

    - name: Install htc
      run: pip install --no-use-pep517 -e .

    - name: Tests
      run: py.test --doctest-modules --import-mode=importlib --collect-only htc
